#! /bin/sh

# Generate headers.mk.
# --------------------
# List all the headers in order to make them part of distribution.

# Use the C locale to have a deterministic sort.
export LC_ALL=C

me=`basename $0`
output=headers.mk

echo "Generating $output..." >&2
rm -f "$output"
cat <<EOF >"$output"
## Generated by \`$me', do not edit by hand.

nobase_include_HEADERS = \\
EOF

find mln -type f -a \( -name '*.hh' -o -name '*.hxx' \)	\
  | sort						\
  | sed -e 's/$/ \\/g' >> headers.mk

last_line=`tail -n 1 headers.mk | sed -e 's/\\\//g'` # remove '\' in last line
sed '$d' < headers.mk > headers.mk.tmp # remove last line
mv headers.mk.tmp headers.mk
echo $last_line >> headers.mk # put the cleaned last line back.
