#! /bin/sh

# Copyright (C) 2005, 2009 EPITA Research and Development Laboratory (LRDE).
#
# This file is part of Olena.
#
# Olena is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2 of the License.
#
# Olena is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Olena.  If not, see <http://www.gnu.org/licenses/>.

# Failures do matter.
set -e
# Tell what's going on.
set -x

mkdir -p _config
touch _config/local-config.rb.in

libtoolize=libtoolize
for l in "$LIBTOOLIZE" glibtoolize libtoolize;
do
  if ($l --version) >/dev/null 2>&1; then
    libtoolize=$l
    break
  fi
done
export LIBTOOLIZE=$libtoolize
# Make the libtool with ltdl
"$libtoolize" --force --copy --automake --ltdl

# Finally, install the GNU Build System.
autoreconf -f -v -i

# FIXME: autoheader does not obey --force.
find . -name 'config.h*.in' -o -name 'local-config.*.in' | xargs touch
