include ../../../igr/Makefile.rules

display_region: display_region.cc
	${CXX} -I../../../ -I../../../../../ ${CXXFLAGS} display_region.cc -o display_region

clean:
	rm -rf *.dump *.p?m *.plot *.log *.csv *.dSYM
