## Generated by gen-examples-outputs-mk.  Do not edit by hand.

$(srcdir)/outputs/accu-right-instanciation.txt: accu-right-instanciation$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/borderthickness.txt: borderthickness$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/box2d-bbox.txt: box2d-bbox$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/domain-display.txt: domain-display$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/dpoint-1.txt: dpoint-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/estim-sites.txt: estim-sites$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/extend.txt: extend$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/extension-ignore.txt: extension-ignore$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill.txt: fill$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-call-1.txt: fill-call-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-imageif-cfun.txt: fill-imageif-cfun$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-part-image.txt: fill-part-image$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-subdomain.txt: fill-subdomain$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-subdomain-shorter.txt: fill-subdomain-shorter$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/first_routine.txt: first_routine$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/forall-piter.txt: forall-piter$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fun-p2v-1.txt: fun-p2v-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/graph-data.txt: graph-data$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/graph-iter.txt: graph-iter$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-has.txt: ima-has$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-save.txt: ima-save$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-size.txt: ima-size$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-1.txt: ima2d-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-2.txt: ima2d-2$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-3.txt: ima2d-3$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-4.txt: ima2d-4$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-5.txt: ima2d-5$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-6-clone.txt: ima2d-6-clone$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-7.txt: ima2d-7$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-rot.txt: ima2d-rot$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/labeling-compute.txt: labeling-compute$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/logical-not.txt: logical-not$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/mln_var.txt: mln_var$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/parray-append.txt: parray-append$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/parray-bbox.txt: parray-bbox$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/paste.txt: paste$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/paste-call-1.txt: paste-call-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/point-1.txt: point-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/predicate-1.txt: predicate-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/win-create-1.txt: win-create-1$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/win-create-2.txt: win-create-2$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto2_first_image.txt: tuto2_first_image$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto3_rw_image.txt: tuto3_rw_image$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto4_genericity_and_algorithms.txt: tuto4_genericity_and_algorithms$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto3_colorize.txt: tuto3_colorize$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto3_println.txt: tuto3_println$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto3_trace.txt: tuto3_trace$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto4_point2d.txt: tuto4_point2d$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto4_site_set_create.txt: tuto4_site_set_create$(EXEEXT)
	rm -f $@.tmp
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

