## Generated by gen-examples-outputs-mk.  Do not edit by hand.

$(srcdir)/outputs/accu-right-instanciation.txt: examples/accu-right-instanciation.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) accu-right-instanciation$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/borderthickness.txt: examples/borderthickness.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) borderthickness$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/box2d-bbox.txt: examples/box2d-bbox.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) box2d-bbox$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/domain-display.txt: examples/domain-display.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) domain-display$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/dpoint-1.txt: examples/dpoint-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) dpoint-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/estim-sites.txt: examples/estim-sites.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) estim-sites$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/extend.txt: examples/extend.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) extend$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/extension-ignore.txt: examples/extension-ignore.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) extension-ignore$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-call-1.txt: examples/fill-call-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-call-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-imageif-cfun.txt: examples/fill-imageif-cfun.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-imageif-cfun$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-part-image.txt: examples/fill-part-image.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-part-image$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-subdomain-shorter.txt: examples/fill-subdomain-shorter.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-subdomain-shorter$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill-subdomain.txt: examples/fill-subdomain.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-subdomain$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fill.txt: examples/fill.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/forall-piter.txt: examples/forall-piter.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) forall-piter$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/fun-p2v-1.txt: examples/fun-p2v-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fun-p2v-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/graph-data.txt: examples/graph-data.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) graph-data$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/graph-iter.txt: examples/graph-iter.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) graph-iter$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-has.txt: examples/ima-has.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-has$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-load.txt: examples/ima-load.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-load$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-save.txt: examples/ima-save.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-save$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima-size.txt: examples/ima-size.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-size$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-1.txt: examples/ima2d-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-2.txt: examples/ima2d-2.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-2$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-3.txt: examples/ima2d-3.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-3$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-4.txt: examples/ima2d-4.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-4$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-5.txt: examples/ima2d-5.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-5$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-6-clone.txt: examples/ima2d-6-clone.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-6-clone$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-7.txt: examples/ima2d-7.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-7$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/ima2d-rot.txt: examples/ima2d-rot.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-rot$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/labeling-compute.txt: examples/labeling-compute.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) labeling-compute$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/logical-not.txt: examples/logical-not.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) logical-not$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/mln_var.txt: examples/mln_var.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) mln_var$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/parray-append.txt: examples/parray-append.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) parray-append$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/parray-bbox.txt: examples/parray-bbox.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) parray-bbox$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/paste-call-1.txt: examples/paste-call-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) paste-call-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/paste.txt: examples/paste.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) paste$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/point-1.txt: examples/point-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) point-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/predicate-1.txt: examples/predicate-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) predicate-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto2_first_image.txt: examples/tuto2_first_image.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto2_first_image$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/colorize.txt: examples/tuto3/colorize.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) colorize$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/first_routine.txt: examples/tuto3/first_routine.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) first_routine$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/println.txt: examples/tuto3/println.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) println$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/trace.txt: examples/tuto3/trace.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) trace$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto3_rw_image.txt: examples/tuto3_rw_image.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_rw_image$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/image.txt: examples/tuto4/image.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) image$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/point2d.txt: examples/tuto4/point2d.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) point2d$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/site_set_create.txt: examples/tuto4/site_set_create.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) site_set_create$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/tuto4_genericity_and_algorithms.txt: examples/tuto4_genericity_and_algorithms.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto4_genericity_and_algorithms$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/win-create-1.txt: examples/win-create-1.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) win-create-1$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

$(srcdir)/outputs/win-create-2.txt: examples/win-create-2.cc
	rm -f $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) win-create-2$(EXEEXT)
	./$< >$@.tmp
	cp -f $@.tmp $@
	rm -f $@.tmp

