## Generated by gen-examples-outputs-mk.  Do not edit by hand.


$(srcdir)/examples/accu-right-instantiation.stamp: examples/accu-right-instantiation.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) accu-right-instantiation$(EXEEXT)
	./accu-right-instantiation$(EXEEXT) >$(srcdir)/outputs/accu-right-instantiation.txt.tmp
	mv $(srcdir)/outputs/accu-right-instantiation.txt.tmp $(srcdir)/outputs/accu-right-instantiation.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/accu-right-instantiation.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/accu-right-instantiation.stamp

$(srcdir)/outputs/accu-right-instantiation.txt: $(srcdir)/examples/accu-right-instantiation.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/accu-right-instantiation.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/accu-right-instantiation.stamp; \
	fi


$(srcdir)/examples/borderthickness.stamp: examples/borderthickness.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) borderthickness$(EXEEXT)
	./borderthickness$(EXEEXT) >$(srcdir)/outputs/borderthickness.txt.tmp
	mv $(srcdir)/outputs/borderthickness.txt.tmp $(srcdir)/outputs/borderthickness.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/borderthickness.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/borderthickness.stamp

$(srcdir)/outputs/borderthickness.txt: $(srcdir)/examples/borderthickness.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/borderthickness.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/borderthickness.stamp; \
	fi


$(srcdir)/examples/box2d-bbox.stamp: examples/box2d-bbox.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) box2d-bbox$(EXEEXT)
	./box2d-bbox$(EXEEXT) >$(srcdir)/outputs/box2d-bbox.txt.tmp
	mv $(srcdir)/outputs/box2d-bbox.txt.tmp $(srcdir)/outputs/box2d-bbox.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/box2d-bbox.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/box2d-bbox.stamp

$(srcdir)/outputs/box2d-bbox.txt: $(srcdir)/examples/box2d-bbox.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/box2d-bbox.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/box2d-bbox.stamp; \
	fi


$(srcdir)/examples/domain-display.stamp: examples/domain-display.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) domain-display$(EXEEXT)
	./domain-display$(EXEEXT) >$(srcdir)/outputs/domain-display.txt.tmp
	mv $(srcdir)/outputs/domain-display.txt.tmp $(srcdir)/outputs/domain-display.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/domain-display.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/domain-display.stamp

$(srcdir)/outputs/domain-display.txt: $(srcdir)/examples/domain-display.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/domain-display.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/domain-display.stamp; \
	fi


$(srcdir)/examples/dpoint-1.stamp: examples/dpoint-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) dpoint-1$(EXEEXT)
	./dpoint-1$(EXEEXT) >$(srcdir)/outputs/dpoint-1.txt.tmp
	mv $(srcdir)/outputs/dpoint-1.txt.tmp $(srcdir)/outputs/dpoint-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/dpoint-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/dpoint-1.stamp

$(srcdir)/outputs/dpoint-1.txt: $(srcdir)/examples/dpoint-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/dpoint-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/dpoint-1.stamp; \
	fi


$(srcdir)/examples/estim-sites.stamp: examples/estim-sites.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) estim-sites$(EXEEXT)
	./estim-sites$(EXEEXT) >$(srcdir)/outputs/estim-sites.txt.tmp
	mv $(srcdir)/outputs/estim-sites.txt.tmp $(srcdir)/outputs/estim-sites.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/estim-sites.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/estim-sites.stamp

$(srcdir)/outputs/estim-sites.txt: $(srcdir)/examples/estim-sites.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/estim-sites.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/estim-sites.stamp; \
	fi


$(srcdir)/examples/extend.stamp: examples/extend.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) extend$(EXEEXT)
	./extend$(EXEEXT) >$(srcdir)/outputs/extend.txt.tmp
	mv $(srcdir)/outputs/extend.txt.tmp $(srcdir)/outputs/extend.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/extend.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/extend.stamp

$(srcdir)/outputs/extend.txt: $(srcdir)/examples/extend.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/extend.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/extend.stamp; \
	fi


$(srcdir)/examples/extension-ignore.stamp: examples/extension-ignore.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) extension-ignore$(EXEEXT)
	./extension-ignore$(EXEEXT) >$(srcdir)/outputs/extension-ignore.txt.tmp
	mv $(srcdir)/outputs/extension-ignore.txt.tmp $(srcdir)/outputs/extension-ignore.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/extension-ignore.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/extension-ignore.stamp

$(srcdir)/outputs/extension-ignore.txt: $(srcdir)/examples/extension-ignore.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/extension-ignore.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/extension-ignore.stamp; \
	fi


$(srcdir)/examples/fill-call-1.stamp: examples/fill-call-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-call-1$(EXEEXT)
	./fill-call-1$(EXEEXT) >$(srcdir)/outputs/fill-call-1.txt.tmp
	mv $(srcdir)/outputs/fill-call-1.txt.tmp $(srcdir)/outputs/fill-call-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill-call-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill-call-1.stamp

$(srcdir)/outputs/fill-call-1.txt: $(srcdir)/examples/fill-call-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill-call-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill-call-1.stamp; \
	fi


$(srcdir)/examples/fill-imageif-cfun.stamp: examples/fill-imageif-cfun.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-imageif-cfun$(EXEEXT)
	./fill-imageif-cfun$(EXEEXT) >$(srcdir)/outputs/fill-imageif-cfun.txt.tmp
	mv $(srcdir)/outputs/fill-imageif-cfun.txt.tmp $(srcdir)/outputs/fill-imageif-cfun.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill-imageif-cfun.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill-imageif-cfun.stamp

$(srcdir)/outputs/fill-imageif-cfun.txt: $(srcdir)/examples/fill-imageif-cfun.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill-imageif-cfun.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill-imageif-cfun.stamp; \
	fi


$(srcdir)/examples/fill-part-image.stamp: examples/fill-part-image.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-part-image$(EXEEXT)
	./fill-part-image$(EXEEXT) >$(srcdir)/outputs/fill-part-image.txt.tmp
	mv $(srcdir)/outputs/fill-part-image.txt.tmp $(srcdir)/outputs/fill-part-image.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill-part-image.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill-part-image.stamp

$(srcdir)/outputs/fill-part-image.txt: $(srcdir)/examples/fill-part-image.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill-part-image.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill-part-image.stamp; \
	fi


$(srcdir)/examples/fill-subdomain-shorter.stamp: examples/fill-subdomain-shorter.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-subdomain-shorter$(EXEEXT)
	./fill-subdomain-shorter$(EXEEXT) >$(srcdir)/outputs/fill-subdomain-shorter.txt.tmp
	mv $(srcdir)/outputs/fill-subdomain-shorter.txt.tmp $(srcdir)/outputs/fill-subdomain-shorter.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill-subdomain-shorter.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill-subdomain-shorter.stamp

$(srcdir)/outputs/fill-subdomain-shorter.txt: $(srcdir)/examples/fill-subdomain-shorter.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill-subdomain-shorter.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill-subdomain-shorter.stamp; \
	fi


$(srcdir)/examples/fill-subdomain.stamp: examples/fill-subdomain.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill-subdomain$(EXEEXT)
	./fill-subdomain$(EXEEXT) >$(srcdir)/outputs/fill-subdomain.txt.tmp
	mv $(srcdir)/outputs/fill-subdomain.txt.tmp $(srcdir)/outputs/fill-subdomain.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill-subdomain.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill-subdomain.stamp

$(srcdir)/outputs/fill-subdomain.txt: $(srcdir)/examples/fill-subdomain.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill-subdomain.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill-subdomain.stamp; \
	fi


$(srcdir)/examples/fill.stamp: examples/fill.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fill$(EXEEXT)
	./fill$(EXEEXT) >$(srcdir)/outputs/fill.txt.tmp
	mv $(srcdir)/outputs/fill.txt.tmp $(srcdir)/outputs/fill.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fill.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fill.stamp

$(srcdir)/outputs/fill.txt: $(srcdir)/examples/fill.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fill.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fill.stamp; \
	fi


$(srcdir)/examples/forall-piter.stamp: examples/forall-piter.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) forall-piter$(EXEEXT)
	./forall-piter$(EXEEXT) >$(srcdir)/outputs/forall-piter.txt.tmp
	mv $(srcdir)/outputs/forall-piter.txt.tmp $(srcdir)/outputs/forall-piter.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/forall-piter.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/forall-piter.stamp

$(srcdir)/outputs/forall-piter.txt: $(srcdir)/examples/forall-piter.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/forall-piter.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/forall-piter.stamp; \
	fi


$(srcdir)/examples/fun-p2v-1.stamp: examples/fun-p2v-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) fun-p2v-1$(EXEEXT)
	./fun-p2v-1$(EXEEXT) >$(srcdir)/outputs/fun-p2v-1.txt.tmp
	mv $(srcdir)/outputs/fun-p2v-1.txt.tmp $(srcdir)/outputs/fun-p2v-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/fun-p2v-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/fun-p2v-1.stamp

$(srcdir)/outputs/fun-p2v-1.txt: $(srcdir)/examples/fun-p2v-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/fun-p2v-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/fun-p2v-1.stamp; \
	fi


$(srcdir)/examples/graph-data.stamp: examples/graph-data.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) graph-data$(EXEEXT)
	./graph-data$(EXEEXT) >$(srcdir)/outputs/graph-data.txt.tmp
	mv $(srcdir)/outputs/graph-data.txt.tmp $(srcdir)/outputs/graph-data.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/graph-data.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/graph-data.stamp

$(srcdir)/outputs/graph-data.txt: $(srcdir)/examples/graph-data.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/graph-data.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/graph-data.stamp; \
	fi


$(srcdir)/examples/graph-iter.stamp: examples/graph-iter.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) graph-iter$(EXEEXT)
	./graph-iter$(EXEEXT) >$(srcdir)/outputs/graph-iter.txt.tmp
	mv $(srcdir)/outputs/graph-iter.txt.tmp $(srcdir)/outputs/graph-iter.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/graph-iter.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/graph-iter.stamp

$(srcdir)/outputs/graph-iter.txt: $(srcdir)/examples/graph-iter.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/graph-iter.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/graph-iter.stamp; \
	fi


$(srcdir)/examples/ima-has.stamp: examples/ima-has.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-has$(EXEEXT)
	./ima-has$(EXEEXT) >$(srcdir)/outputs/ima-has.txt.tmp
	mv $(srcdir)/outputs/ima-has.txt.tmp $(srcdir)/outputs/ima-has.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima-has.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima-has.stamp

$(srcdir)/outputs/ima-has.txt: $(srcdir)/examples/ima-has.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima-has.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima-has.stamp; \
	fi


$(srcdir)/examples/ima-load.stamp: examples/ima-load.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-load$(EXEEXT)
	./ima-load$(EXEEXT) >$(srcdir)/outputs/ima-load.txt.tmp
	mv $(srcdir)/outputs/ima-load.txt.tmp $(srcdir)/outputs/ima-load.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima-load.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima-load.stamp

$(srcdir)/outputs/ima-load.txt: $(srcdir)/examples/ima-load.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima-load.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima-load.stamp; \
	fi


$(srcdir)/examples/ima-save.stamp: examples/ima-save.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-save$(EXEEXT)
	./ima-save$(EXEEXT) >$(srcdir)/outputs/ima-save.txt.tmp
	mv $(srcdir)/outputs/ima-save.txt.tmp $(srcdir)/outputs/ima-save.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima-save.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima-save.stamp

$(srcdir)/outputs/ima-save.txt: $(srcdir)/examples/ima-save.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima-save.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima-save.stamp; \
	fi


$(srcdir)/examples/ima-size.stamp: examples/ima-size.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima-size$(EXEEXT)
	./ima-size$(EXEEXT) >$(srcdir)/outputs/ima-size.txt.tmp
	mv $(srcdir)/outputs/ima-size.txt.tmp $(srcdir)/outputs/ima-size.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima-size.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima-size.stamp

$(srcdir)/outputs/ima-size.txt: $(srcdir)/examples/ima-size.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima-size.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima-size.stamp; \
	fi


$(srcdir)/examples/ima2d-1.stamp: examples/ima2d-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-1$(EXEEXT)
	./ima2d-1$(EXEEXT) >$(srcdir)/outputs/ima2d-1.txt.tmp
	mv $(srcdir)/outputs/ima2d-1.txt.tmp $(srcdir)/outputs/ima2d-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-1.stamp

$(srcdir)/outputs/ima2d-1.txt: $(srcdir)/examples/ima2d-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-1.stamp; \
	fi


$(srcdir)/examples/ima2d-2.stamp: examples/ima2d-2.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-2$(EXEEXT)
	./ima2d-2$(EXEEXT) >$(srcdir)/outputs/ima2d-2.txt.tmp
	mv $(srcdir)/outputs/ima2d-2.txt.tmp $(srcdir)/outputs/ima2d-2.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-2.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-2.stamp

$(srcdir)/outputs/ima2d-2.txt: $(srcdir)/examples/ima2d-2.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-2.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-2.stamp; \
	fi


$(srcdir)/examples/ima2d-3.stamp: examples/ima2d-3.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-3$(EXEEXT)
	./ima2d-3$(EXEEXT) >$(srcdir)/outputs/ima2d-3.txt.tmp
	mv $(srcdir)/outputs/ima2d-3.txt.tmp $(srcdir)/outputs/ima2d-3.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-3.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-3.stamp

$(srcdir)/outputs/ima2d-3.txt: $(srcdir)/examples/ima2d-3.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-3.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-3.stamp; \
	fi


$(srcdir)/examples/ima2d-4.stamp: examples/ima2d-4.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-4$(EXEEXT)
	./ima2d-4$(EXEEXT) >$(srcdir)/outputs/ima2d-4.txt.tmp
	mv $(srcdir)/outputs/ima2d-4.txt.tmp $(srcdir)/outputs/ima2d-4.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-4.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-4.stamp

$(srcdir)/outputs/ima2d-4.txt: $(srcdir)/examples/ima2d-4.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-4.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-4.stamp; \
	fi


$(srcdir)/examples/ima2d-5.stamp: examples/ima2d-5.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-5$(EXEEXT)
	./ima2d-5$(EXEEXT) >$(srcdir)/outputs/ima2d-5.txt.tmp
	mv $(srcdir)/outputs/ima2d-5.txt.tmp $(srcdir)/outputs/ima2d-5.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-5.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-5.stamp

$(srcdir)/outputs/ima2d-5.txt: $(srcdir)/examples/ima2d-5.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-5.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-5.stamp; \
	fi


$(srcdir)/examples/ima2d-6-clone.stamp: examples/ima2d-6-clone.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-6-clone$(EXEEXT)
	./ima2d-6-clone$(EXEEXT) >$(srcdir)/outputs/ima2d-6-clone.txt.tmp
	mv $(srcdir)/outputs/ima2d-6-clone.txt.tmp $(srcdir)/outputs/ima2d-6-clone.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-6-clone.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-6-clone.stamp

$(srcdir)/outputs/ima2d-6-clone.txt: $(srcdir)/examples/ima2d-6-clone.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-6-clone.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-6-clone.stamp; \
	fi


$(srcdir)/examples/ima2d-7.stamp: examples/ima2d-7.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-7$(EXEEXT)
	./ima2d-7$(EXEEXT) >$(srcdir)/outputs/ima2d-7.txt.tmp
	mv $(srcdir)/outputs/ima2d-7.txt.tmp $(srcdir)/outputs/ima2d-7.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-7.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-7.stamp

$(srcdir)/outputs/ima2d-7.txt: $(srcdir)/examples/ima2d-7.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-7.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-7.stamp; \
	fi


$(srcdir)/examples/ima2d-rot.stamp: examples/ima2d-rot.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) ima2d-rot$(EXEEXT)
	./ima2d-rot$(EXEEXT) >$(srcdir)/outputs/ima2d-rot.txt.tmp
	mv $(srcdir)/outputs/ima2d-rot.txt.tmp $(srcdir)/outputs/ima2d-rot.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/ima2d-rot.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/ima2d-rot.stamp

$(srcdir)/outputs/ima2d-rot.txt: $(srcdir)/examples/ima2d-rot.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/ima2d-rot.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/ima2d-rot.stamp; \
	fi


$(srcdir)/examples/labeling-compute.stamp: examples/labeling-compute.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) labeling-compute$(EXEEXT)
	./labeling-compute$(EXEEXT) >$(srcdir)/outputs/labeling-compute.txt.tmp
	mv $(srcdir)/outputs/labeling-compute.txt.tmp $(srcdir)/outputs/labeling-compute.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/labeling-compute.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/labeling-compute.stamp

$(srcdir)/outputs/labeling-compute.txt: $(srcdir)/examples/labeling-compute.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/labeling-compute.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/labeling-compute.stamp; \
	fi


$(srcdir)/examples/logical-not.stamp: examples/logical-not.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) logical-not$(EXEEXT)
	./logical-not$(EXEEXT) >$(srcdir)/outputs/logical-not.txt.tmp
	mv $(srcdir)/outputs/logical-not.txt.tmp $(srcdir)/outputs/logical-not.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/logical-not.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/logical-not.stamp

$(srcdir)/outputs/logical-not.txt: $(srcdir)/examples/logical-not.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/logical-not.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/logical-not.stamp; \
	fi


$(srcdir)/examples/mln_var.stamp: examples/mln_var.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) mln_var$(EXEEXT)
	./mln_var$(EXEEXT) >$(srcdir)/outputs/mln_var.txt.tmp
	mv $(srcdir)/outputs/mln_var.txt.tmp $(srcdir)/outputs/mln_var.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/mln_var.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/mln_var.stamp

$(srcdir)/outputs/mln_var.txt: $(srcdir)/examples/mln_var.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/mln_var.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/mln_var.stamp; \
	fi


$(srcdir)/examples/parray-append.stamp: examples/parray-append.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) parray-append$(EXEEXT)
	./parray-append$(EXEEXT) >$(srcdir)/outputs/parray-append.txt.tmp
	mv $(srcdir)/outputs/parray-append.txt.tmp $(srcdir)/outputs/parray-append.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/parray-append.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/parray-append.stamp

$(srcdir)/outputs/parray-append.txt: $(srcdir)/examples/parray-append.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/parray-append.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/parray-append.stamp; \
	fi


$(srcdir)/examples/parray-bbox.stamp: examples/parray-bbox.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) parray-bbox$(EXEEXT)
	./parray-bbox$(EXEEXT) >$(srcdir)/outputs/parray-bbox.txt.tmp
	mv $(srcdir)/outputs/parray-bbox.txt.tmp $(srcdir)/outputs/parray-bbox.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/parray-bbox.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/parray-bbox.stamp

$(srcdir)/outputs/parray-bbox.txt: $(srcdir)/examples/parray-bbox.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/parray-bbox.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/parray-bbox.stamp; \
	fi


$(srcdir)/examples/paste-call-1.stamp: examples/paste-call-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) paste-call-1$(EXEEXT)
	./paste-call-1$(EXEEXT) >$(srcdir)/outputs/paste-call-1.txt.tmp
	mv $(srcdir)/outputs/paste-call-1.txt.tmp $(srcdir)/outputs/paste-call-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/paste-call-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/paste-call-1.stamp

$(srcdir)/outputs/paste-call-1.txt: $(srcdir)/examples/paste-call-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/paste-call-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/paste-call-1.stamp; \
	fi


$(srcdir)/examples/paste.stamp: examples/paste.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) paste$(EXEEXT)
	./paste$(EXEEXT) >$(srcdir)/outputs/paste.txt.tmp
	mv $(srcdir)/outputs/paste.txt.tmp $(srcdir)/outputs/paste.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/paste.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/paste.stamp

$(srcdir)/outputs/paste.txt: $(srcdir)/examples/paste.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/paste.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/paste.stamp; \
	fi


$(srcdir)/examples/point-1.stamp: examples/point-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) point-1$(EXEEXT)
	./point-1$(EXEEXT) >$(srcdir)/outputs/point-1.txt.tmp
	mv $(srcdir)/outputs/point-1.txt.tmp $(srcdir)/outputs/point-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/point-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/point-1.stamp

$(srcdir)/outputs/point-1.txt: $(srcdir)/examples/point-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/point-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/point-1.stamp; \
	fi


$(srcdir)/examples/predicate-1.stamp: examples/predicate-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) predicate-1$(EXEEXT)
	./predicate-1$(EXEEXT) >$(srcdir)/outputs/predicate-1.txt.tmp
	mv $(srcdir)/outputs/predicate-1.txt.tmp $(srcdir)/outputs/predicate-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/predicate-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/predicate-1.stamp

$(srcdir)/outputs/predicate-1.txt: $(srcdir)/examples/predicate-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/predicate-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/predicate-1.stamp; \
	fi


$(srcdir)/examples/tuto2_first_image.stamp: examples/tuto2_first_image.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto2_first_image$(EXEEXT)
	./tuto2_first_image$(EXEEXT) >$(srcdir)/outputs/tuto2_first_image.txt.tmp
	mv $(srcdir)/outputs/tuto2_first_image.txt.tmp $(srcdir)/outputs/tuto2_first_image.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto2_first_image.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto2_first_image.stamp

$(srcdir)/outputs/tuto2_first_image.txt: $(srcdir)/examples/tuto2_first_image.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto2_first_image.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto2_first_image.stamp; \
	fi


$(srcdir)/examples/tuto3/colorize.stamp: examples/tuto3/colorize.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_colorize$(EXEEXT)
	./tuto3_colorize$(EXEEXT) >$(srcdir)/outputs/tuto3_colorize.txt.tmp
	mv $(srcdir)/outputs/tuto3_colorize.txt.tmp $(srcdir)/outputs/tuto3_colorize.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto3/colorize.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto3/colorize.stamp

$(srcdir)/outputs/tuto3_colorize.txt: $(srcdir)/examples/tuto3/colorize.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto3/colorize.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto3/colorize.stamp; \
	fi


$(srcdir)/examples/tuto3/first_routine.stamp: examples/tuto3/first_routine.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_first_routine$(EXEEXT)
	./tuto3_first_routine$(EXEEXT) >$(srcdir)/outputs/tuto3_first_routine.txt.tmp
	mv $(srcdir)/outputs/tuto3_first_routine.txt.tmp $(srcdir)/outputs/tuto3_first_routine.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto3/first_routine.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto3/first_routine.stamp

$(srcdir)/outputs/tuto3_first_routine.txt: $(srcdir)/examples/tuto3/first_routine.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto3/first_routine.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto3/first_routine.stamp; \
	fi


$(srcdir)/examples/tuto3/println.stamp: examples/tuto3/println.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_println$(EXEEXT)
	./tuto3_println$(EXEEXT) >$(srcdir)/outputs/tuto3_println.txt.tmp
	mv $(srcdir)/outputs/tuto3_println.txt.tmp $(srcdir)/outputs/tuto3_println.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto3/println.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto3/println.stamp

$(srcdir)/outputs/tuto3_println.txt: $(srcdir)/examples/tuto3/println.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto3/println.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto3/println.stamp; \
	fi


$(srcdir)/examples/tuto3/trace.stamp: examples/tuto3/trace.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_trace$(EXEEXT)
	./tuto3_trace$(EXEEXT) >$(srcdir)/outputs/tuto3_trace.txt.tmp
	mv $(srcdir)/outputs/tuto3_trace.txt.tmp $(srcdir)/outputs/tuto3_trace.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto3/trace.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto3/trace.stamp

$(srcdir)/outputs/tuto3_trace.txt: $(srcdir)/examples/tuto3/trace.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto3/trace.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto3/trace.stamp; \
	fi


$(srcdir)/examples/tuto3_rw_image.stamp: examples/tuto3_rw_image.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto3_rw_image$(EXEEXT)
	./tuto3_rw_image$(EXEEXT) >$(srcdir)/outputs/tuto3_rw_image.txt.tmp
	mv $(srcdir)/outputs/tuto3_rw_image.txt.tmp $(srcdir)/outputs/tuto3_rw_image.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto3_rw_image.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto3_rw_image.stamp

$(srcdir)/outputs/tuto3_rw_image.txt: $(srcdir)/examples/tuto3_rw_image.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto3_rw_image.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto3_rw_image.stamp; \
	fi


$(srcdir)/examples/tuto4/image.stamp: examples/tuto4/image.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto4_image$(EXEEXT)
	./tuto4_image$(EXEEXT) >$(srcdir)/outputs/tuto4_image.txt.tmp
	mv $(srcdir)/outputs/tuto4_image.txt.tmp $(srcdir)/outputs/tuto4_image.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto4/image.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto4/image.stamp

$(srcdir)/outputs/tuto4_image.txt: $(srcdir)/examples/tuto4/image.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto4/image.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto4/image.stamp; \
	fi


$(srcdir)/examples/tuto4/point2d.stamp: examples/tuto4/point2d.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto4_point2d$(EXEEXT)
	./tuto4_point2d$(EXEEXT) >$(srcdir)/outputs/tuto4_point2d.txt.tmp
	mv $(srcdir)/outputs/tuto4_point2d.txt.tmp $(srcdir)/outputs/tuto4_point2d.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto4/point2d.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto4/point2d.stamp

$(srcdir)/outputs/tuto4_point2d.txt: $(srcdir)/examples/tuto4/point2d.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto4/point2d.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto4/point2d.stamp; \
	fi


$(srcdir)/examples/tuto4/site_set_create.stamp: examples/tuto4/site_set_create.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto4_site_set_create$(EXEEXT)
	./tuto4_site_set_create$(EXEEXT) >$(srcdir)/outputs/tuto4_site_set_create.txt.tmp
	mv $(srcdir)/outputs/tuto4_site_set_create.txt.tmp $(srcdir)/outputs/tuto4_site_set_create.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto4/site_set_create.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto4/site_set_create.stamp

$(srcdir)/outputs/tuto4_site_set_create.txt: $(srcdir)/examples/tuto4/site_set_create.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto4/site_set_create.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto4/site_set_create.stamp; \
	fi


$(srcdir)/examples/tuto4_genericity_and_algorithms.stamp: examples/tuto4_genericity_and_algorithms.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) tuto4_genericity_and_algorithms$(EXEEXT)
	./tuto4_genericity_and_algorithms$(EXEEXT) >$(srcdir)/outputs/tuto4_genericity_and_algorithms.txt.tmp
	mv $(srcdir)/outputs/tuto4_genericity_and_algorithms.txt.tmp $(srcdir)/outputs/tuto4_genericity_and_algorithms.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/tuto4_genericity_and_algorithms.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/tuto4_genericity_and_algorithms.stamp

$(srcdir)/outputs/tuto4_genericity_and_algorithms.txt: $(srcdir)/examples/tuto4_genericity_and_algorithms.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/tuto4_genericity_and_algorithms.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/tuto4_genericity_and_algorithms.stamp; \
	fi


$(srcdir)/examples/win-create-1.stamp: examples/win-create-1.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) win-create-1$(EXEEXT)
	./win-create-1$(EXEEXT) >$(srcdir)/outputs/win-create-1.txt.tmp
	mv $(srcdir)/outputs/win-create-1.txt.tmp $(srcdir)/outputs/win-create-1.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/win-create-1.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/win-create-1.stamp

$(srcdir)/outputs/win-create-1.txt: $(srcdir)/examples/win-create-1.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/win-create-1.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/win-create-1.stamp; \
	fi


$(srcdir)/examples/win-create-2.stamp: examples/win-create-2.cc
	@rm -f $@.tmp
	@touch $@.tmp
	$(MAKE) $(AM_MAKEFLAGS) win-create-2$(EXEEXT)
	./win-create-2$(EXEEXT) >$(srcdir)/outputs/win-create-2.txt.tmp
	mv $(srcdir)/outputs/win-create-2.txt.tmp $(srcdir)/outputs/win-create-2.txt
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/examples/win-create-2.stamp
MAINTAINERCLEANFILES += $(srcdir)/examples/win-create-2.stamp

$(srcdir)/outputs/win-create-2.txt: $(srcdir)/examples/win-create-2.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $(srcdir)/examples/win-create-2.stamp; \
	  $(MAKE) $(AM_MAKEFLAGS) $(srcdir)/examples/win-create-2.stamp; \
	fi
