#! /bin/sh

## FIXME: Don't use `echo -n', as echo's options are not portable.
##
## http://www.gnu.org/software/autoconf/manual/html_node/Limitations-of-Builtins.html#Limitations-of-Builtins
##
## As an ugly workaround, use `printf' instead.  The right approach
## would be to only emit lines ended with newlines.
ECHO_N=printf

# Use the C locale to have a deterministic sort.
export LC_ALL=C

for dir in figures outputs examples; do
  OUT="$dir/$dir.mk"
  echo "## Generated by ../generate_dist_files, do not modify." > $OUT
  echo >>$OUT
  $ECHO_N "EXTRA_DIST += " >> $OUT
  for ftype in cc.raw p*m txt; do
    for file in `find $dir -mindepth 1 -name *.$ftype | sort`; do
      echo " \\" >> $OUT
      $ECHO_N $file >> $OUT
    done
  done
  echo "" >> $OUT
done
