## Generated by gen-make-variable.  Do not edit by hand.

PBM_FIGURES = \
  $(srcdir)/figures/fill-subdomain-1.pbm \
  $(srcdir)/figures/ima_save.pbm \
  $(srcdir)/figures/labeling-compute-1.pbm \
  $(srcdir)/figures/logical-not-1.pbm \
  $(srcdir)/figures/logical-not-2.pbm \
  $(srcdir)/figures/logical-not-3.pbm \
  $(srcdir)/figures/tuto2_first_image-1.pbm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-3.pbm
