## Generated by gen-make-variable.  Do not edit by hand.

PGM_FIGURES = \
  $(srcdir)/figures/tuto3_colorize-1.pgm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-7.pgm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-8.pgm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-9.pgm
