## Generated by gen-make-variable.  Do not edit by hand.

PPM_FIGURES = \
  $(srcdir)/figures/extend-1.ppm \
  $(srcdir)/figures/extend-2.ppm \
  $(srcdir)/figures/extend-3.ppm \
  $(srcdir)/figures/extend-4.ppm \
  $(srcdir)/figures/extend-5.ppm \
  $(srcdir)/figures/fill-1.ppm \
  $(srcdir)/figures/fill-2.ppm \
  $(srcdir)/figures/fill-imageif-cfun-1.ppm \
  $(srcdir)/figures/fill-subdomain-2.ppm \
  $(srcdir)/figures/fill-subdomain-3.ppm \
  $(srcdir)/figures/fill-subdomain-4.ppm \
  $(srcdir)/figures/fill-subimage-cfun-1.ppm \
  $(srcdir)/figures/ima2d-rot-1.ppm \
  $(srcdir)/figures/ima2d-rot-2.ppm \
  $(srcdir)/figures/labeling-compute-2.ppm \
  $(srcdir)/figures/tuto3_colorize-2.ppm \
  $(srcdir)/figures/tuto3_rw_image-1.ppm \
  $(srcdir)/figures/tuto3_rw_image-2.ppm \
  $(srcdir)/figures/tuto3_rw_image-3.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-1.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-2.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-4.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-5.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-6.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-7.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-8.ppm \
  $(srcdir)/figures/tuto4_genericity_and_algorithms-9.ppm
