## Generated by gen-split-outputs-mk.  Do not edit by hand.

SPLIT_OUTPUTS = \
  $(srcdir)/outputs/split/graph-iter-1.txt \
  $(srcdir)/outputs/split/graph-iter-2.txt \
  $(srcdir)/outputs/split/graph-iter-3.txt \
  $(srcdir)/outputs/split/graph-iter-4.txt \
  $(srcdir)/outputs/split/tuto3_println-1.txt \
  $(srcdir)/outputs/split/tuto3_println-2.txt \
  $(srcdir)/outputs/split/tuto4_site_set_create-1.txt \
  $(srcdir)/outputs/split/tuto4_site_set_create-2.txt \
  $(srcdir)/outputs/split/tuto4_site_set_create-3.txt


$(srcdir)/outputs/split/graph-iter.txt.stamp: $(srcdir)/outputs/graph-iter.txt
	@rm -f $@.tmp
	@touch $@.tmp
	$(srcdir)/tools/split_sample.sh $< txt "" $(srcdir)/outputs/split
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/outputs/split/graph-iter.txt.stamp
MAINTAINERCLEANFILES += $(srcdir)/outputs/split/graph-iter.txt.stamp

$(srcdir)/outputs/split/graph-iter-1.txt $(srcdir)/outputs/split/graph-iter-2.txt $(srcdir)/outputs/split/graph-iter-3.txt $(srcdir)/outputs/split/graph-iter-4.txt: $(srcdir)/outputs/split/graph-iter.txt.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $<; \
	  $(MAKE) $(AM_MAKEFLAGS) $<; \
	fi


$(srcdir)/outputs/split/tuto3_println.txt.stamp: $(srcdir)/outputs/tuto3_println.txt
	@rm -f $@.tmp
	@touch $@.tmp
	$(srcdir)/tools/split_sample.sh $< txt "" $(srcdir)/outputs/split
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/outputs/split/tuto3_println.txt.stamp
MAINTAINERCLEANFILES += $(srcdir)/outputs/split/tuto3_println.txt.stamp

$(srcdir)/outputs/split/tuto3_println-1.txt $(srcdir)/outputs/split/tuto3_println-2.txt: $(srcdir)/outputs/split/tuto3_println.txt.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $<; \
	  $(MAKE) $(AM_MAKEFLAGS) $<; \
	fi


$(srcdir)/outputs/split/tuto4_site_set_create.txt.stamp: $(srcdir)/outputs/tuto4_site_set_create.txt
	@rm -f $@.tmp
	@touch $@.tmp
	$(srcdir)/tools/split_sample.sh $< txt "" $(srcdir)/outputs/split
	@mv -f $@.tmp $@
EXTRA_DIST += $(srcdir)/outputs/split/tuto4_site_set_create.txt.stamp
MAINTAINERCLEANFILES += $(srcdir)/outputs/split/tuto4_site_set_create.txt.stamp

$(srcdir)/outputs/split/tuto4_site_set_create-1.txt $(srcdir)/outputs/split/tuto4_site_set_create-2.txt $(srcdir)/outputs/split/tuto4_site_set_create-3.txt: $(srcdir)/outputs/split/tuto4_site_set_create.txt.stamp
## Recover from the removal of $@
	@if test -f $@; then :; else \
	  rm -f $<; \
	  $(MAKE) $(AM_MAKEFLAGS) $<; \
	fi
