## Generated by ../generate_dist_files, do not modify ##
EXTRA_DIST +=  \
examples/cpp_issue.cc \
examples/sub_image.cc \
examples/sub_image_if.cc \
examples/p_vaccess.cc \
examples/win_multiple.cc \
examples/image2d.cc \
examples/image_plain.cc \
examples/p_run.cc \
examples/proxy.cc \
examples/p_array.2.cc \
examples/examples.mk \
examples/for_Z.cc \
examples/image_if.cc \
examples/p_key.cc \
examples/p_mutable_array_of.cc \
examples/p_queue.cc \
examples/image_flat.cc \
examples/p_image.cc \
examples/box.cc \
examples/p_line2d.cc \
examples/p_array.cc \
examples/accu.cc \
examples/p_key.2.cc \
examples/window.cc \
examples/image_safe.cc \
examples/vec.cc
