All_warnings = -ansi -pedantic -Wabi -Wctor-dtor-privacy -Wnon-virtual-dtor \
	       -Wreorder -Weffc++ -Wno-deprecated -Wstrict-null-sentinel \
	       -Wno-non-template-friend -Wold-style-cast -Woverloaded-virtual \
	       -Wno-pmf-conversions -Wsign-promo -fsyntax-only-pedantic-errors \
	       -w -Wextra -Wall -Waddress -Waggregate-return -Wno-attributes \
	       -Wcast-align -Wcast-qual -Wchar-subscripts -Wcomment -Wconversion \
	       -Wno-deprecated-declarations -Wdisabled-optimization -Wno-div-by-zero \
	       -Wno-endif-labels -Werror -Wfatal-errors -Wfloat-equal -Wformat \
	       -Wformat=2 -Wno-format-extra-args -Wformat-nonliteral \
	       -Wformat-security -Wformat-y2k -Wimplicit -Wimport -Wno-import \
	       -Winit-self -Winline -Wno-invalid-offsetof -Winvalid-pch \
	       -Wlarger-than-1 -Wunsafe-loop-optimizations -Wlong-long \
	       -Wmissing-braces -Wmissing-field-initializers \
	       -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn \
	       -Wno-multichar -Wno-overflow -Woverlength-strings -Wpacked -Wpadded \
	       -Wparentheses -Wpointer-arith -Wredundant-decls -Wreturn-type \
	       -Wsequence-point -Wshadow -Wsign-compare -Wstack-protector \
	       -Wstrict-aliasing -Wstrict-overflow -Wswitch -Wswitch-default \
	       -Wswitch-enum -Wsystem-headers -Wtrigraphs -Wundef -Wuninitialized \
	       -Wunknown-pragmas -Wno-pragmas -Wunreachable-code -Wunused \
	       -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value \
	       -Wunused-variable -Wvariadic-macros -Wvolatile-register-var \
	       -Wwrite-strings \

all:
	g++-4.2 -ansi -pedantic -I../.. first_test.cc -o first_test
