#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: $0 <mln_path>"
fi

HEADERS=`find $1 -name "*.hh" | grep -vE "*.spe.hh" | grep -v "mln/core/concept/doc" | sed -e 's/.*\/mln\/\(.*\)/mln\/\1/g' | sed 's/\.\.\/\.\.\///g'`

rm -f Makefile.am
rm -f *.hh *.cc

#build Makefile.am
echo "## Process this file through Automake to create Makefile.in -*- Makefile -*-" >> Makefile.am
echo ""                                             >> Makefile.am
echo "include \$(top_srcdir)/milena/tests/tests.mk" >> Makefile.am
echo ""                                             >> Makefile.am
echo -n "check_PROGRAMS = "                         >> Makefile.am

for i in $HEADERS; do
    FILE_CC=`echo $i | sed 's/[/.]/_/g' | sed 's/_hh/\.cc/g'`

#Build .cc
    cat > $FILE_CC << EOF
// Unit test for $i.
// Generated by $0, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <$i>
#include <$i>

int main()
{
  // Nothing.
}
EOF

#build Makefile.am
    TARGET=`echo "${FILE_CC}" | sed 's/\.cc//'`
    echo " \\" >> Makefile.am
    echo -n "${TARGET}" >> Makefile.am
done

#build Makefile.am
echo "" >> Makefile.am
echo "" >> Makefile.am
for i in $HEADERS; do
    FILE_CC=`echo $i | sed 's/[/.]/_/g' | sed 's/_hh/\.cc/g'`
    NAME=`echo $FILE_CC | sed 's/\.cc//g'`
    echo "${NAME}_SOURCES = $FILE_CC" >> Makefile.am
done
echo "" >> Makefile.am
echo "TESTS = \$(check_PROGRAMS)" >> Makefile.am
