// Unit test for mln/core/image/complex_neighborhood_piter.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/core/image/complex_neighborhood_piter.hh>
#include <mln/core/image/complex_neighborhood_piter.hh>

int main()
{
  // Nothing.
}
