// Unit test for mln/geom/delta.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/geom/delta.hh>
#include <mln/geom/delta.hh>

int main()
{
  // Nothing.
}
