// Unit test for mln/fun/x2v/bilinear.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/x2v/bilinear.hh>
#include <mln/fun/x2v/bilinear.hh>

int main()
{
  // Nothing.
}
