// Unit test for mln/core/routine/duplicate.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/core/routine/duplicate.hh>
#include <mln/core/routine/duplicate.hh>

int main()
{
  // Nothing.
}
