// Unit test for mln/io/essential.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/io/essential.hh>
#include <mln/io/essential.hh>

int main()
{
  // Nothing.
}
