// Unit test for mln/fun/meta/blue.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/meta/blue.hh>
#include <mln/fun/meta/blue.hh>

int main()
{
  // Nothing.
}
