// Unit test for mln/geom/ncols.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/geom/ncols.hh>
#include <mln/geom/ncols.hh>

int main()
{
  // Nothing.
}
