// Unit test for mln/fun/vv2v/diff_abs.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/vv2v/diff_abs.hh>
#include <mln/fun/vv2v/diff_abs.hh>

int main()
{
  // Nothing.
}
