// Unit test for mln/core/internal/neighb_niter_impl.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/core/internal/neighb_niter_impl.hh>
#include <mln/core/internal/neighb_niter_impl.hh>

int main()
{
  // Nothing.
}
