// Unit test for mln/metal/unconst.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/metal/unconst.hh>
#include <mln/metal/unconst.hh>

int main()
{
  // Nothing.
}
