// Unit test for mln/fun/c.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/c.hh>
#include <mln/fun/c.hh>

int main()
{
  // Nothing.
}
