// Unit test for mln/metal/bexpr.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/metal/bexpr.hh>
#include <mln/metal/bexpr.hh>

int main()
{
  // Nothing.
}
