// Unit test for mln/opt/element.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/opt/element.hh>
#include <mln/opt/element.hh>

int main()
{
  // Nothing.
}
