// Unit test for mln/literal/black.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/literal/black.hh>
#include <mln/literal/black.hh>

int main()
{
  // Nothing.
}
