// Unit test for mln/set/has.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/set/has.hh>
#include <mln/set/has.hh>

int main()
{
  // Nothing.
}
