// Unit test for mln/fun/p2v/iota.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/p2v/iota.hh>
#include <mln/fun/p2v/iota.hh>

int main()
{
  // Nothing.
}
