// Unit test for mln/data/memcpy_.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/data/memcpy_.hh>
#include <mln/data/memcpy_.hh>

int main()
{
  // Nothing.
}
