// Unit test for mln/core/concept/mesh.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/core/concept/mesh.hh>
#include <mln/core/concept/mesh.hh>

int main()
{
  // Nothing.
}
