// Unit test for mln/logical/xor.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/logical/xor.hh>
#include <mln/logical/xor.hh>

int main()
{
  // Nothing.
}
