// Unit test for mln/data/fill_with_image.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/data/fill_with_image.hh>
#include <mln/data/fill_with_image.hh>

int main()
{
  // Nothing.
}
