// Unit test for mln/convert/impl/from_image_to_site_set.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/convert/impl/from_image_to_site_set.hh>
#include <mln/convert/impl/from_image_to_site_set.hh>

int main()
{
  // Nothing.
}
