// Unit test for mln/value/graylevel.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/value/graylevel.hh>
#include <mln/value/graylevel.hh>

int main()
{
  // Nothing.
}
