// Unit test for mln/convert/to_upper_window.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/convert/to_upper_window.hh>
#include <mln/convert/to_upper_window.hh>

int main()
{
  // Nothing.
}
