// Unit test for mln/morpho/hit_or_miss.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/morpho/hit_or_miss.hh>
#include <mln/morpho/hit_or_miss.hh>

int main()
{
  // Nothing.
}
