// Unit test for mln/labeling/background.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/labeling/background.hh>
#include <mln/labeling/background.hh>

int main()
{
  // Nothing.
}
