// Unit test for mln/make/pix.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/make/pix.hh>
#include <mln/make/pix.hh>

int main()
{
  // Nothing.
}
