// Unit test for mln/canvas/browsing/dir_struct_elt_incr_update.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/canvas/browsing/dir_struct_elt_incr_update.hh>
#include <mln/canvas/browsing/dir_struct_elt_incr_update.hh>

int main()
{
  // Nothing.
}
