// Unit test for mln/trace/warning.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/trace/warning.hh>
#include <mln/trace/warning.hh>

int main()
{
  // Nothing.
}
