// Unit test for mln/pw/var.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/pw/var.hh>
#include <mln/pw/var.hh>

int main()
{
  // Nothing.
}
