// Unit test for mln/util/internal/graph_iter.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/util/internal/graph_iter.hh>
#include <mln/util/internal/graph_iter.hh>

int main()
{
  // Nothing.
}
