// Unit test for mln/transform/internal/all.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/transform/internal/all.hh>
#include <mln/transform/internal/all.hh>

int main()
{
  // Nothing.
}
