// Unit test for mln/value/concept/structured.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/value/concept/structured.hh>
#include <mln/value/concept/structured.hh>

int main()
{
  // Nothing.
}
