// Unit test for mln/essential/routine.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/essential/routine.hh>
#include <mln/essential/routine.hh>

int main()
{
  // Nothing.
}
