// Unit test for mln/registration/get_rtransf.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/registration/get_rtransf.hh>
#include <mln/registration/get_rtransf.hh>

int main()
{
  // Nothing.
}
