// Unit test for mln/topo/complex_iterators.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/topo/complex_iterators.hh>
#include <mln/topo/complex_iterators.hh>

int main()
{
  // Nothing.
}
