// Unit test for mln/trait/ch_value.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/trait/ch_value.hh>
#include <mln/trait/ch_value.hh>

int main()
{
  // Nothing.
}
