// Unit test for mln/make/h_mat.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/make/h_mat.hh>
#include <mln/make/h_mat.hh>

int main()
{
  // Nothing.
}
