// Unit test for mln/fun/v2v/inc.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/v2v/inc.hh>
#include <mln/fun/v2v/inc.hh>

int main()
{
  // Nothing.
}
