// Unit test for mln/accu/land_basic.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/accu/land_basic.hh>
#include <mln/accu/land_basic.hh>

int main()
{
  // Nothing.
}
