// Unit test for mln/topo/face_data.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/topo/face_data.hh>
#include <mln/topo/face_data.hh>

int main()
{
  // Nothing.
}
