// Unit test for mln/linear/lap.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/linear/lap.hh>
#include <mln/linear/lap.hh>

int main()
{
  // Nothing.
}
