// Unit test for mln/morpho/top_hat.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/morpho/top_hat.hh>
#include <mln/morpho/top_hat.hh>

int main()
{
  // Nothing.
}
