// Unit test for mln/fun/i2v/all_to.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/i2v/all_to.hh>
#include <mln/fun/i2v/all_to.hh>

int main()
{
  // Nothing.
}
