// Unit test for mln/canvas/browsing/backdiagonal2d.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/canvas/browsing/backdiagonal2d.hh>
#include <mln/canvas/browsing/backdiagonal2d.hh>

int main()
{
  // Nothing.
}
