// Unit test for mln/morpho/opening_area_on_vertices.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/morpho/opening_area_on_vertices.hh>
#include <mln/morpho/opening_area_on_vertices.hh>

int main()
{
  // Nothing.
}
