// Unit test for mln/border/find.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/border/find.hh>
#include <mln/border/find.hh>

int main()
{
  // Nothing.
}
