// Unit test for mln/value/other.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/value/other.hh>
#include <mln/value/other.hh>

int main()
{
  // Nothing.
}
