// Unit test for mln/binarization/binarization.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/binarization/binarization.hh>
#include <mln/binarization/binarization.hh>

int main()
{
  // Nothing.
}
