// Unit test for mln/labeling/flat_zones.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/labeling/flat_zones.hh>
#include <mln/labeling/flat_zones.hh>

int main()
{
  // Nothing.
}
