// Unit test for mln/registration/icp.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/registration/icp.hh>
#include <mln/registration/icp.hh>

int main()
{
  // Nothing.
}
