// Unit test for mln/morpho/thinning.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/morpho/thinning.hh>
#include <mln/morpho/thinning.hh>

int main()
{
  // Nothing.
}
