// Unit test for mln/topo/internal/complex_relative_iterator_sequence.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/topo/internal/complex_relative_iterator_sequence.hh>
#include <mln/topo/internal/complex_relative_iterator_sequence.hh>

int main()
{
  // Nothing.
}
