// Unit test for mln/fun/x2p/closest_point.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/x2p/closest_point.hh>
#include <mln/fun/x2p/closest_point.hh>

int main()
{
  // Nothing.
}
