// Unit test for mln/draw/box.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/draw/box.hh>
#include <mln/draw/box.hh>

int main()
{
  // Nothing.
}
