// Unit test for mln/value/hsl.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/value/hsl.hh>
#include <mln/value/hsl.hh>

int main()
{
  // Nothing.
}
