// Unit test for mln/canvas/browsing/snake_fwd.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/canvas/browsing/snake_fwd.hh>
#include <mln/canvas/browsing/snake_fwd.hh>

int main()
{
  // Nothing.
}
