// Unit test for mln/trace/quiet.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/trace/quiet.hh>
#include <mln/trace/quiet.hh>

int main()
{
  // Nothing.
}
