// Unit test for mln/util/internal/vertex_impl.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/util/internal/vertex_impl.hh>
#include <mln/util/internal/vertex_impl.hh>

int main()
{
  // Nothing.
}
