// Unit test for mln/norm/l1.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/norm/l1.hh>
#include <mln/norm/l1.hh>

int main()
{
  // Nothing.
}
