// Unit test for mln/level/compare.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/level/compare.hh>
#include <mln/level/compare.hh>

int main()
{
  // Nothing.
}
