// Unit test for mln/debug/println_with_border.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/debug/println_with_border.hh>
#include <mln/debug/println_with_border.hh>

int main()
{
  // Nothing.
}
