// Unit test for mln/fun/internal/ch_function_value_impl.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/internal/ch_function_value_impl.hh>
#include <mln/fun/internal/ch_function_value_impl.hh>

int main()
{
  // Nothing.
}
