// Unit test for mln/fun/l2l/relabel.hh.
// Generated by ./build_unit_test.sh, do not modify.

// Include the file twice, so we detect missing inclusion guards.
#include <mln/fun/l2l/relabel.hh>
#include <mln/fun/l2l/relabel.hh>

int main()
{
  // Nothing.
}
