
#ifndef PROJECTION_HH
# define PROJECTION_HH

# include <assert.h>

namespace mln
{

  namespace projection
  {

    template <typename P, typename T1, typename T2>
    float fill_Xk(const p_array<P>& Ck,
                  std::pair<T1,T2>& map,
                  p_array<P>& Xk)
    {
      assert(Ck.npoints() == Xk.npoints());
      
      float err = 0.f;

      for (size_t i = 0; i < Ck.npoints(); ++i)
        {
          //FIXME: bof
          //if (map.second.has(Ck[i]))
          //{
              //x[i] := Ck[i] closest point in X
              Xk.hook_()[i] = map.second(Ck[i]);
              //err := Distance between Ck[i] and its closest point
              err += map.first(Ck[i]);
              //}
        }
      return err /= Ck.npoints();
    }
    
    template <typename P>
    void de_base(// input
                 const p_array<P>& Ck,
                 const p_array<P>& X,
                 // inout
                 p_array<P>& Xk,
                 float& err)
    {
      assert(Ck.npoints() == Xk.npoints());

      err = 0.f;

      for (size_t i = 0; i < Ck.npoints(); ++i)
        {
          algebra::vec<P::dim,float> Cki = Ck[i];
          algebra::vec<P::dim,float> best_x = X[0];
          float best_d = norm::l2(Cki - best_x);
          for (size_t j = 1; j < X.npoints(); ++j)
            {
              algebra::vec<P::dim,float> Xj = X[j];
              float d = norm::l2(Cki - Xj);
              if (d < best_d)
                {
                  best_d = d;
                  best_x = Xj;
                }
            }
          Xk.hook_()[i] = algebra::to_point<P>(best_x);
          err += best_d;
        }
      err /= Ck.npoints();
    }
  
        
    template <typename P>
    void memo(// input
             const p_array<P>& Ck,
             const p_array<P>& X,
             // inout
             p_array<P>& Xk,
             float& err)
    {
      //FIXME: remove static
      //FIXME: domain generated by X and C's domain?
      static image3d<point3d> map(1000,1000,10);
      static image3d<bool> mapset(1000,1000,10);
      
      assert(Ck.npoints() == Xk.npoints());
      
      err = 0.f;
    
      for (size_t i = 0; i < Ck.npoints(); ++i)
        {
          float best_d;
          if (mapset(Ck[i]) == false)
            {
              algebra::vec<P::dim,float> Cki = Ck[i];
              algebra::vec<P::dim,float> best_x = X[0];
              best_d = norm::l2(Cki - best_x);
              for (size_t j = 1; j < X.npoints(); ++j)
                {
                  algebra::vec<P::dim,float> Xj = X[j];
                  float d = norm::l2(Cki - Xj);
                  if (d < best_d)
                    {
                      best_d = d;
                      best_x = Xj;
                    }
                }
              Xk.hook_()[i] = algebra::to_point<P>(best_x);
              map(Ck[i]) = Xk[i];
              mapset(Ck[i]) = true;
            }
          else
            {
              Xk.hook_()[i] = map(Ck[i]);
            }
          err += best_d;
        }
      err /= Ck.npoints();
    }
    
  } // end of namespace projection
  
} // end of namespace mln

#endif // ndef PROJECTION_HH
