#!/bin/sh

for dir in samples figures outputs examples; do
  OUT="$dir/$dir.mk"
  echo "## Generated by ../generate_dist_files, do not modify ##" > $OUT
  echo -n "EXTRA_DIST += " >> $OUT
  for file in `find $dir`; do
    echo " \\" >> $OUT
    echo -n $file >> $OUT
  done
  echo "" >> $OUT
done
