require 'pathname'
# STDERR.puts "MK: #{ARGV.inspect}"
def usage
  STDERR.puts "Usage: #$0 <dest-file>"
  STDERR.puts "ac_subst_vars will be read from stdin"
  exit
end
usage if ARGV.size != 1
out_path = Pathname.new ARGV.shift
args = STDIN.read.split(/\s+/)
out_path.chmod(0644) if out_path.exist?
out_path.open('w') do |out|
  out.puts "# Generated by mk_local_config_rb_in.rb"
  out.puts "# dest-file: #{out_path}"
  out.puts "# ac_subst_vars: #{args.join(' ')}"
  out.puts "AC_CONFIG = {"
  args.each do |arg|
    out.puts "  :#{arg} => '@#{arg}@',"
  end
  out.puts "}"
end
out_path.chmod(0444)
