require 'rbconfig'

def gen_m4 ( config )
  config.each_key do |k|
    name = "RUBY_#{k}"
    puts %Q{
      AC_SUBST([#{name}],
        RUBY([
          val = Config::CONFIG[%q[#{k}]]
          val = val.to_s.gsub(%q['], %q['"'"'])
          %q['] + val + %q[']
        ]))
      AC_DEFINE([#{name}], $#{name},
        [Contains Config::CONFIG['#{k}'] (generated by rbconfig_gen.rb)])
    }
  end
end

gen_m4(Config::CONFIG)
