#!/bin/sh

# Copyright (C) 2009 EPITA Research and Development Laboratory
# (LRDE)
#
# This file is part of the Milena Library.  This library is free
# software; you can redistribute it and/or modify it under the terms
# of the GNU General Public License version 2 as published by the
# Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this library; see the file COPYING.  If not, write to
# the Free Software Foundation, 51 Franklin Street, Fifth Floor,
# Boston, MA 02111-1307, USA.

if [ $# -ne 2 ]; then
  echo "Usage: `basename $0` <path to mln> <output_log_dir>" 1>&2
  exit 1;
fi


path_to_mln=`dirname $1`

echo "" > $2/missing_all_hh.log
echo "" > $2/not_included_in_all_hh.log

cd $path_to_mln

# Checking local all.hh
for dir in `find mln -mindepth 1 -type d`; do

  if ! [ -e "$dir/all.hh" ]; then
    echo "WARNING: no all.hh header in $dir" >&2
    echo "$dir/all.hh" >> $2/missing_all_hh.log
    continue
  fi

  for f in `ls $dir/*.hh | grep -vE '*.spe.hh'`; do
    if [ "`basename $f`" != "all.hh" ]; then
      result=`grep "include <$f>" $dir/all.hh`
      if [ -z "$result" ]; then
	echo "  WARNING $f is not included in $dir/all.hh" >&2
	echo "$f" >> $2/not_included_in_all_hh.log
      fi
    fi
  done

done

#cd -
