#!/bin/sh

# Copyright (C) 2009 EPITA Research and Development Laboratory (LRDE).
#
# This file is part of Olena.
#
# Olena is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2 of the License.
#
# Olena is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Olena.  If not, see <http://www.gnu.org/licenses/>.

if [ -z "$MILENA_DEVTOOLS_PATH" ]; then
    echo "MILENA_DEVTOOLS_PATH is not set." >&2
    exit 1
fi


source $MILENA_DEVTOOLS_PATH/make_report_utils.sh
source $MILENA_DEVTOOLS_PATH/devtools_utils.sh


check()
{
    local mln_path=`mln_based_path $1/all.hh`
    local abs_path=`abs_filepath $1/all.hh`

# Checking local all.hh
    for dir in `find "$abs_path" -type d`; do
	if ! [ -e "$dir/all.hh" ]; then
	    path=`mln_based_path $dir/all.hh`
	    if [ -z "$2" ]; then
		echo "WARNING: no all.hh header in $path" >&2
	    else
		close_dir_entry $2
		open_dir_entry "$path" $2
	    fi

	    continue
	fi
    done
}



if [ $# -lt 1 ]; then
  echo "Usage: $0 [--report output.html] <dir1> <dir2> ..." >&2
  echo "-----"
  echo "  Directories without all.hh files will be printed out."
  echo "  A HTML report may be also generated."
  exit 1
fi

report=""
if [ "$1" == "--report" ]; then
  shift
  report=$1
  rm -f $1
  touch $1
  shift
fi

if ! [ -z "$report" ]; then
  prepare_report $report "Missing all.hh headers."
fi

while [ $# -ne 0 ]; do
  check $1 "$report"
  shift
done

if ! [ -z "$report" ]; then
  end_report $report
fi
