#! /bin/sh

# Copyright (C) 2009 EPITA Research and Development Laboratory
# (LRDE)
#
# This file is part of the Milena Library.  This library is free
# software; you can redistribute it and/or modify it under the terms
# of the GNU General Public License version 2 as published by the
# Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this library; see the file COPYING.  If not, write to
# the Free Software Foundation, 51 Franklin Street, Fifth Floor,
# Boston, MA 02111-1307, USA.

failed_tests=0
all_tests=0

check_directory ()
{
  echo "Current directories: $1 $2"

  for file in `ls $1`; do

    if [ -f ${1}/$file ]; then
      ext=${file##*.}
      base=${file%.*}

      if [ "$ext" = "hh" -a \
	   "${base##*.}" != "spe" ]; then
	test_file=${file%.hh}.cc
	all_tests=$(($all_tests + 1))

	if [ -f ${2}/$test_file ]; then
	  echo "\t\e[0;32mOK\e[m $file <-> $test_file" > /dev/null
	else
	  if [ "$file" != "all.hh"  -a \
	    "$file" != "essential.hh" ]; then
	    echo "\tFAIL Test \"$test_file\" does not exist."
	    failed_tests=$(($failed_tests + 1))
	  fi
	fi

      fi

    fi

    if [ -d ${1}/$file ]; then
      if [ -d ${2}/$file ]; then
	echo ""
	check_directory ${1}/$file ${2}/$file
      else
	if [ "$file" != "internal" ]; then
	  echo "FAIL Test directory \"${2}/$file\" does not exist."
	fi
      fi
    fi

  done
}

if [ $# -ne 2 ]; then
  echo "Usage: ./check_test_source_has_test mln/ tests/"
  exit 1
fi

echo "Source directory: $1"
echo "Test directory: $2"
echo "---"

if [ -d ${1} ]; then
  if [ -d ${2} ]; then
    check_directory ${1} ${2}
  else
    echo "\e[0;31mFAIL\e[m Test directory $2 does not exist."
  fi
else
  echo "\e[0;31mFAIL\e[m Source directory $1 does not exist."
fi

echo "\n====="
echo "Missing tests: $failed_tests"

