#!/bin/sh

# Copyright (C) 2009 EPITA Research and Development Laboratory (LRDE).
#
# This file is part of Olena.
#
# Olena is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2 of the License.
#
# Olena is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Olena.  If not, see <http://www.gnu.org/licenses/>.


if [ -z "$MILENA_DEVTOOLS_PATH" ]; then
    echo "MILENA_DEVTOOLS_PATH is not set." >&2
    exit 1
fi


source $MILENA_DEVTOOLS_PATH/make_report_utils.sh
source $MILENA_DEVTOOLS_PATH/devtools_utils.sh


last_path=""
check()
{
    f=`basename $1`
    abs_dir=`abs_filepath $1`
    mln_based_dir=`mln_based_path $1`


    # Omitting internal directories.
    # They are not supposed to contain all.hh files.
    if [ -z "`echo $abs_dir | grep -v internal`" ]; then
	return
    fi

    # Checking local all.hh
    if ! [ -e "$abs_dir/all.hh" ]; then
	echo "WARNING: no all.hh header in $mln_based_dir" >&2
	return
    fi

    result=`grep "include <$mln_based_dir/$f>" $abs_dir/all.hh`
    if [ -z "$result" ]; then
	if [ -z "$report" ]; then
	    echo "  WARNING $f is not included in $mln_based_dir/all.hh" >&2
	else
	    if [ "$last_path" != "$mln_based_dir" ]; then
		close_dir_entry $2
		open_dir_entry "$mln_based_dir" $2
		last_path="$mln_based_dir"
	    fi
	    echo "<li>$f</li>" >> $2
	fi
    fi
}



if [ $# -lt 1 ]; then
  echo "Usage: $0 [--report output.html] <file1> <file2> ..." >&2
  echo "-----"
  echo " Names of files which are not included in their respective"
  echo " all.hh file will be printed out."
  echo " A HTML report may be also generated."
  exit 1
fi

report=""
if [ "$1" == "--report" ]; then
  shift
  report=$1
  rm -f $1
  touch $1
  shift
fi

if ! [ -z "$report" ]; then
  prepare_report $report "Files not included in all.hh."
fi


while [ $# -ne 0 ]; do
    if [ "`basename $1`" != "all.hh" ] && [ "`basename $1`" != "essential.hh" ]; then

	check $1 "$report"
    fi
    shift
done


if ! [ -z "$report" ]; then
  end_report $report
fi
