.TH "OLENA" "1" "" "" ""
.SH "NAME"
Olena
.SH "DESCRIPTION"
.PP
An Image Processing Platform
.SH "AUTHOR"
.PP
This manual page was written by the Olena Team <olena@lrde.epita.fr> for
the \fBDebian\fP system (but may be used by others).
.PP
It is in the public domain, so you can do whatever you want with it.
