## Generated by ../generate_dist_files, do not modify.

EXTRA_DIST +=  \
examples/accu-wrong-instanciation.cc.raw \
examples/fill-proto.cc.raw \
examples/ima2d-restricted-1.cc.raw \
examples/ima2d-restricted-2.cc.raw \
examples/ima2d-restricted-3.cc.raw \
examples/tuto3/fill_non_generic.cc.raw
