CXX = g++
CXXFLAGS = -DNDEBUG -O1
INC = -I../../ -I../../../../

hq2x: hq2x.cc
	${CXX} ${CXXFLAGS} ${INC} $^ -o hq2x

hq3x: hq3x.cc
	${CXX} ${CXXFLAGS} ${INC} $^ -o hq3x

hq4x: hq4x.cc
	${CXX} ${CXXFLAGS} ${INC} $^ -o hq4x
