// Copyright (C) 2007 EPITA Research and Development Laboratory (LRDE)
// Copyright (C) 2008 EPITA Research and Development Laboratory (LRDE)
// Copyright (C) 2009 EPITA Research and Development Laboratory (LRDE)
//
// This file is part of Olena.
//
// Olena is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation, version 2 of the License.
//
// Olena is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Olena.  If not, see <http://www.gnu.org/licenses/>.
//
// As a special exception, you may use this file as part of a free
// software project without restriction.  Specifically, if other files
// instantiate templates or use macros or inline functions from this
// file, or you compile this file and link it with other files to produce
// an executable, this file does not by itself cause the resulting
// executable to be covered by the GNU General Public License.  This
// exception does not however invalidate any other reasons why the
// executable file might be covered by the GNU General Public License.

#ifndef MLN_IMG_PATH_HH
# define MLN_IMG_PATH_HH

# define IMG_PATH    "/home/green/git/img"
# define RET_PATH    "/home/green/git/result"

# define INIM_IMG_PATH         IMG_PATH"/inim"
# define INIM_BG_IMG_PATH      INIM_IMG_PATH"/bg"
# define INIM_FG_IMG_PATH      INIM_IMG_PATH"/fg"
# define INIM_IN_IMG_PATH      INIM_IMG_PATH"/in"

# define OLENA_IMG_PATH        IMG_PATH"/olena"

# define ICDAR_IMG_PATH            IMG_PATH"/icdar"
# define ICDAR_100P_IMG_PATH       ICDAR_IMG_PATH"/100p"
# define ICDAR_100P_PPM_IMG_PATH   ICDAR_100P_IMG_PATH"/ppm"
# define ICDAR_100P_PGM_IMG_PATH   ICDAR_100P_IMG_PATH"/pgm"
# define ICDAR_100P_PBM_IMG_PATH   ICDAR_100P_IMG_PATH"/pbm"
# define ICDAR_100P_THICK_IMG_PATH ICDAR_100P_IMG_PATH"/gradient_thick"
# define ICDAR_100P_THIN_IMG_PATH  ICDAR_100P_IMG_PATH"/gradient_thin"

# define ICDAR_50P_IMG_PATH        ICDAR_IMG_PATH"/50p"
# define ICDAR_50P_PPM_IMG_PATH    ICDAR_50P_IMG_PATH"/ppm"
# define ICDAR_50P_PGM_IMG_PATH    ICDAR_50P_IMG_PATH"/pgm"
# define ICDAR_50P_PBM_IMG_PATH    ICDAR_50P_IMG_PATH"/pbm"

# define ICDAR_20P_IMG_PATH                ICDAR_IMG_PATH"/20p"
# define ICDAR_20P_TEXT_ONLY_IMG_PATH      ICDAR_20P_IMG_PATH"/text-only"
# define ICDAR_20P_TEXT_COLOR_IMG_PATH     ICDAR_20P_IMG_PATH"/text-color"
# define ICDAR_20P_TEXT_PHOTO_IMG_PATH     ICDAR_20P_IMG_PATH"/text-photo"
# define ICDAR_20P_GMP30_IMG_PATH          ICDAR_20P_IMG_PATH"/gimp-pal-30"
# define ICDAR_20P_MGK30_IMG_PATH	   ICDAR_20P_IMG_PATH"/magick-pal-30"
# define ICDAR_20P_GMP20_IMG_PATH          ICDAR_20P_IMG_PATH"/gimp-pal-20"
# define ICDAR_20P_MGK20_IMG_PATH	   ICDAR_20P_IMG_PATH"/magick-pal-20"
# define ICDAR_20P_GMP10_IMG_PATH          ICDAR_20P_IMG_PATH"/gimp-pal-10"
# define ICDAR_20P_MGK10_IMG_PATH	   ICDAR_20P_IMG_PATH"/magick-pal-10"
# define ICDAR_20P_INPUT_IMG_PATH	   ICDAR_20P_IMG_PATH"/ppm"
# define ICDAR_20P_CROP_IMG_PATH           ICDAR_20P_IMG_PATH"/crop"
# define ICDAR_20P_PGM_IMG_PATH            ICDAR_20P_IMG_PATH"/pgm"
# define ICDAR_20P_PPM_IMG_PATH            ICDAR_20P_IMG_PATH"/ppm"
# define ICDAR_20P_PBM_IMG_PATH            ICDAR_20P_IMG_PATH"/pbm"

# define AFP_IMG_PATH                      IMG_PATH"/afp"
# define AFP_GMP30_IMG_PATH		   AFP_IMG_PATH"/gimp-pal-30"
# define AFP_GMP20_IMG_PATH		   AFP_IMG_PATH"/gimp-pal-20"
# define AFP_GMP10_IMG_PATH		   AFP_IMG_PATH"/gimp-pal-10"
# define AFP_MGK30_IMG_PATH		   AFP_IMG_PATH"/magick-pal-30"
# define AFP_MGK20_IMG_PATH		   AFP_IMG_PATH"/magick-pal-20"
# define AFP_MGK10_IMG_PATH		   AFP_IMG_PATH"/magick-pal-10"
# define AFP_INPUT_IMG_PATH                AFP_IMG_PATH"/ppm"
# define AFP_PPM_IMG_PATH                  AFP_IMG_PATH"/ppm"
# define AFP_JPG_IMG_PATH                  AFP_IMG_PATH"/jpg"

# define ANNOTATING_1_IMG_PATH             IMG_PATH"/annotating-1"
# define ANNOTATING_1_BILL_IMG_PATH        ANNOTATING_1_IMG_PATH"/bill"
# define ANNOTATING_1_FAX_IMG_PATH         ANNOTATING_1_IMG_PATH"/fax"
# define ANNOTATING_1_HANDWRITTEN_IMG_PATH ANNOTATING_1_IMG_PATH"/handwritten"
# define ANNOTATING_1_LOGO_IMG_PATH        ANNOTATING_1_IMG_PATH"/logo"
# define ANNOTATING_1_MAP_IMG_PATH         ANNOTATING_1_IMG_PATH"/map"
# define ANNOTATING_1_SCREENSHOT_IMG_PATH  ANNOTATING_1_IMG_PATH"/screenshot"
# define ANNOTATING_1_SLIDE_IMG_PATH       ANNOTATING_1_IMG_PATH"/slide"
# define ANNOTATING_1_TYPED_IMG_PATH       ANNOTATING_1_IMG_PATH"/typed"
# define ANNOTATING_1_PHOTO_IMG_PATH       ANNOTATING_1_IMG_PATH"/photo"

# define ANNOTATING_2_IMG_PATH             IMG_PATH"/annotating-2"
# define ANNOTATING_2_BILL_IMG_PATH        ANNOTATING_2_IMG_PATH"/bill"
# define ANNOTATING_2_FAX_IMG_PATH         ANNOTATING_2_IMG_PATH"/fax"
# define ANNOTATING_2_HANDWRITTEN_IMG_PATH ANNOTATING_2_IMG_PATH"/handwritten"
# define ANNOTATING_2_LOGO_IMG_PATH        ANNOTATING_2_IMG_PATH"/logo"
# define ANNOTATING_2_MAP_IMG_PATH         ANNOTATING_2_IMG_PATH"/map"
# define ANNOTATING_2_SCREENSHOT_IMG_PATH  ANNOTATING_2_IMG_PATH"/screenshot"
# define ANNOTATING_2_SLIDE_IMG_PATH       ANNOTATING_2_IMG_PATH"/slide"
# define ANNOTATING_2_TYPED_IMG_PATH       ANNOTATING_2_IMG_PATH"/typed"
# define ANNOTATING_2_PHOTO_IMG_PATH       ANNOTATING_2_IMG_PATH"/photo"

// result directories
# define ANNOTATING_RET_PATH             RET_PATH"/annotating"

# define ANNOTATING_ICDAR_RET_PATH       ANNOTATING_RET_PATH"/icdar"

# define ANNOTATING_ICDAR_INPUT_RET_PATH   ANNOTATING_ICDAR_RET_PATH"/input"
# define ANNOTATING_ICDAR_H_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_INPUT_RET_PATH ANNOTATING_ICDAR_INPUT_RET_PATH"/b"

# define ANNOTATING_ICDAR_GMP30_RET_PATH ANNOTATING_ICDAR_RET_PATH"/gimp-pal-30"
# define ANNOTATING_ICDAR_H_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_GMP30_RET_PATH ANNOTATING_ICDAR_GMP30_RET_PATH"/b"

# define ANNOTATING_ICDAR_GMP20_RET_PATH ANNOTATING_ICDAR_RET_PATH"/gimp-pal-20"
# define ANNOTATING_ICDAR_H_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_GMP20_RET_PATH ANNOTATING_ICDAR_GMP20_RET_PATH"/b"

# define ANNOTATING_ICDAR_GMP10_RET_PATH ANNOTATING_ICDAR_RET_PATH"/gimp-pal-10"
# define ANNOTATING_ICDAR_H_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_GMP10_RET_PATH ANNOTATING_ICDAR_GMP10_RET_PATH"/b"

# define ANNOTATING_ICDAR_MGK30_RET_PATH ANNOTATING_ICDAR_RET_PATH"/magick-pal-30"
# define ANNOTATING_ICDAR_H_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_MGK30_RET_PATH ANNOTATING_ICDAR_MGK30_RET_PATH"/b"

# define ANNOTATING_ICDAR_MGK20_RET_PATH ANNOTATING_ICDAR_RET_PATH"/magick-pal-20"
# define ANNOTATING_ICDAR_H_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_MGK20_RET_PATH ANNOTATING_ICDAR_MGK20_RET_PATH"/b"

# define ANNOTATING_ICDAR_MGK10_RET_PATH ANNOTATING_ICDAR_RET_PATH"/magick-pal-10"
# define ANNOTATING_ICDAR_H_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/h"
# define ANNOTATING_ICDAR_S_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/s"
# define ANNOTATING_ICDAR_V_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/v"
# define ANNOTATING_ICDAR_R_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/r"
# define ANNOTATING_ICDAR_G_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/g"
# define ANNOTATING_ICDAR_B_MGK10_RET_PATH ANNOTATING_ICDAR_MGK10_RET_PATH"/b"




# define ANNOTATING_AFP_RET_PATH         ANNOTATING_RET_PATH"/afp"

# define ANNOTATING_AFP_INPUT_RET_PATH   ANNOTATING_AFP_RET_PATH"/input"
# define ANNOTATING_AFP_H_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/h"
# define ANNOTATING_AFP_S_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/s"
# define ANNOTATING_AFP_V_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/v"
# define ANNOTATING_AFP_R_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/r"
# define ANNOTATING_AFP_G_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/g"
# define ANNOTATING_AFP_B_INPUT_RET_PATH ANNOTATING_AFP_INPUT_RET_PATH"/b"

# define ANNOTATING_AFP_GMP30_RET_PATH   ANNOTATING_AFP_RET_PATH"/gimp-pal-30"
# define ANNOTATING_AFP_H_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/h"
# define ANNOTATING_AFP_S_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/s"
# define ANNOTATING_AFP_V_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/v"
# define ANNOTATING_AFP_R_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/r"
# define ANNOTATING_AFP_G_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/g"
# define ANNOTATING_AFP_B_GMP30_RET_PATH ANNOTATING_AFP_GMP30_RET_PATH"/b"

# define ANNOTATING_AFP_GMP20_RET_PATH   ANNOTATING_AFP_RET_PATH"/gimp-pal-20"
# define ANNOTATING_AFP_H_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/h"
# define ANNOTATING_AFP_S_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/s"
# define ANNOTATING_AFP_V_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/v"
# define ANNOTATING_AFP_R_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/r"
# define ANNOTATING_AFP_G_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/g"
# define ANNOTATING_AFP_B_GMP20_RET_PATH ANNOTATING_AFP_GMP20_RET_PATH"/b"

# define ANNOTATING_AFP_GMP10_RET_PATH   ANNOTATING_AFP_RET_PATH"/gimp-pal-10"
# define ANNOTATING_AFP_H_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/h"
# define ANNOTATING_AFP_S_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/s"
# define ANNOTATING_AFP_V_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/v"
# define ANNOTATING_AFP_R_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/r"
# define ANNOTATING_AFP_G_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/g"
# define ANNOTATING_AFP_B_GMP10_RET_PATH ANNOTATING_AFP_GMP10_RET_PATH"/b"

# define ANNOTATING_AFP_MGK30_RET_PATH   ANNOTATING_AFP_RET_PATH"/magick-pal-30"
# define ANNOTATING_AFP_H_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/h"
# define ANNOTATING_AFP_S_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/s"
# define ANNOTATING_AFP_V_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/v"
# define ANNOTATING_AFP_R_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/r"
# define ANNOTATING_AFP_G_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/g"
# define ANNOTATING_AFP_B_MGK30_RET_PATH ANNOTATING_AFP_MGK30_RET_PATH"/b"

# define ANNOTATING_AFP_MGK20_RET_PATH   ANNOTATING_AFP_RET_PATH"/magick-pal-20"
# define ANNOTATING_AFP_H_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/h"
# define ANNOTATING_AFP_S_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/s"
# define ANNOTATING_AFP_V_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/v"
# define ANNOTATING_AFP_R_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/r"
# define ANNOTATING_AFP_G_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/g"
# define ANNOTATING_AFP_B_MGK20_RET_PATH ANNOTATING_AFP_MGK20_RET_PATH"/b"

# define ANNOTATING_AFP_MGK10_RET_PATH   ANNOTATING_AFP_RET_PATH"/magick-pal-10"
# define ANNOTATING_AFP_H_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/h"
# define ANNOTATING_AFP_S_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/s"
# define ANNOTATING_AFP_V_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/v"
# define ANNOTATING_AFP_R_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/r"
# define ANNOTATING_AFP_G_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/g"
# define ANNOTATING_AFP_B_MGK10_RET_PATH ANNOTATING_AFP_MGK10_RET_PATH"/b"


# define ANNOTATING_BILL_RET_PATH        ANNOTATING_RET_PATH"/bill"
# define ANNOTATING_FAX_RET_PATH         ANNOTATING_RET_PATH"/fax"
# define ANNOTATING_HANDWRITTEN_RET_PATH ANNOTATING_RET_PATH"/handwritten"
# define ANNOTATING_LOGO_RET_PATH        ANNOTATING_RET_PATH"/logo"
# define ANNOTATING_MAP_RET_PATH         ANNOTATING_RET_PATH"/map"
# define ANNOTATING_SCREENSHOT_RET_PATH  ANNOTATING_RET_PATH"/screenshot"
# define ANNOTATING_SLIDE_RET_PATH       ANNOTATING_RET_PATH"/slide"
# define ANNOTATING_TYPED_RET_PATH       ANNOTATING_RET_PATH"/typed"
# define ANNOTATING_PHOTO_RET_PATH       ANNOTATING_RET_PATH"/photo"

# define ANNOTATING_ICDAR_ACHROMATISM_RET_PATH ANNOTATING_ICDAR_RET_PATH"/achromatism"


#endif // ! MLN_IMG_PATH_HH
