## Generated by ../generate_dist_files, do not modify.

EXTRA_DIST +=  \
figures/extend-1.ppm \
figures/ima2d-rot-2.ppm \
figures/tuto3_rw_image-1.ppm \
figures/logical-not-2.pbm \
figures/fill-subdomain-2.ppm \
figures/tuto4_genericity_and_algorithms-9.pgm \
figures/labeling-compute-2.ppm \
figures/tuto4_genericity_and_algorithms-7.pgm \
figures/tuto4_genericity_and_algorithms-5.ppm \
figures/ima2d-rot-1.ppm \
figures/fill-subdomain-3.ppm \
figures/tuto4_genericity_and_algorithms-9.ppm \
figures/logical-not-1.pbm \
figures/ima_save.pbm \
figures/tuto2_first_image-1.pbm \
figures/fill-subimage-cfun-1.ppm \
figures/extend-3.ppm \
figures/fill-subdomain-4.ppm \
figures/colorize-1.pgm \
figures/tuto4_genericity_and_algorithms-7.ppm \
figures/tuto4_genericity_and_algorithms-6.ppm \
figures/extend-5.ppm \
figures/logical-not-3.pbm \
figures/colorize-2.ppm \
figures/tuto4_genericity_and_algorithms-3.pbm \
figures/tuto4_genericity_and_algorithms-1.ppm \
figures/extend-4.ppm \
figures/fill-2.ppm \
figures/tuto4_genericity_and_algorithms-8.ppm \
figures/labeling-compute-1.pbm \
figures/tuto3_rw_image-3.ppm \
figures/tuto4_genericity_and_algorithms-4.ppm \
figures/tuto4_genericity_and_algorithms-8.pgm \
figures/extend-2.ppm \
figures/tuto4_genericity_and_algorithms-2.ppm \
figures/fill-subdomain-1.pbm \
figures/fill-1.ppm \
figures/tuto3_rw_image-2.ppm
