// Copyright (C) 2001, 2002, 2003, 2004, 2005, 2006, 2007 EPITA
// Research and Development Laboratory
//
// This file is part of the Olena Library.  This library is free
// software; you can redistribute it and/or modify it under the terms
// of the GNU General Public License version 2 as published by the
// Free Software Foundation.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this library; see the file COPYING.  If not, write to
// the Free Software Foundation, 51 Franklin Street, Fifth Floor,
// Boston, MA 02111-1307, USA.
//
// As a special exception, you may use this file as part of a free
// software library without restriction.  Specifically, if other files
// instantiate templates or use macros or inline functions from this
// file, or you compile this file and link it with other files to
// produce an executable, this file does not by itself cause the
// resulting executable to be covered by the GNU General Public
// License.  This exception does not however invalidate any other
// reasons why the executable file might be covered by the GNU General
// Public License.

#ifndef MLN_IO_TIKZ_SAVE_HEADER_HH
# define MLN_IO_TIKZ_SAVE_HEADER_HH

/*!
 * \file   mln/io/tikz/save_header.hh
 *
 * \brief  Define a function which saves header for TIKZ image.
 *
 */

# include <iostream>
# include <fstream>

namespace mln
{

  namespace io
  {

# ifndef MLN_INCLUDE_ONLY

    namespace tikz
    {

      template <typename I>
      inline
      void save_header(const I& ima,
		       const std::string& filename,
		       std::ofstream& file)
      {
	if (! file)
	{
	  std::cerr << "error: cannot open file '" << filename
		    << "'!";
	  abort();
	}

	file << "% Generated by milena 1.0  http://olena.lrde.epita.fr" << std::endl;
	file << "% EPITA Research and Development Laboratory (LRDE)" << std::endl;

	file << "\\documentclass[12pt,a4paper]{article}" << std::endl;
	file << "\\usepackage{tikz}" << std::endl;

	file << "\\begin{document}" << std::endl;
	file << "\\begin{tikzpicture}" << std::endl;
	file << "\\tikzstyle{every node}=[transform shape, draw,shape=rectangle, minimum width=1cm, minimum height=1cm]" << std::endl;

      }

    } // end of namespace mln::io::tikz


# endif // ! MLN_INCLUDE_ONLY

  } // end of namespace mln::io

} // end of namespace mln


#endif // ! MLN_IO_TIKZ_SAVE_HEADER_HH
