######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 1 10:28:31 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui
INCLUDEPATH += . src ../../../ ../../../milena
DEFINES += NDEBUG

# Input
HEADERS += src/mainwindow.hh
FORMS += ui/mainwindow.ui
SOURCES += src/main.cc src/mainwindow.cc

RESOURCES = review.qrc
