n_cmpt: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt.cc -DNDEBUG -O1 -o n_cmpt

n_cmpt2: n_cmpt2.hh n_cmpt2.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt2.cc -DNDEBUG -O1 -o n_cmpt2

debug: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra  n_cmpt.cc -g -g3 -DNDEBUG -O1 -o n_cmpt
