n_cmpt6: n_cmpt6.hh n_cmpt6.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt6.cc -DNDEBUG -O1 -o n_cmpt6

n_cmpt5: n_cmpt5.hh n_cmpt5.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt5.cc -DNDEBUG -O1 -o n_cmpt5

n_cmpt4: n_cmpt4.hh n_cmpt4.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt4.cc -DNDEBUG -O1 -o n_cmpt4

n_cmpt3: n_cmpt3.hh n_cmpt3.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt3.cc -DNDEBUG -O1 -o n_cmpt3

n_cmpt2: n_cmpt2.hh n_cmpt2.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt2.cc -DNDEBUG -O1 -o n_cmpt2

n_cmpt: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt.cc -DNDEBUG -O1 -o n_cmtp


nwst: nwst.hh nwst.cc
	g++ -I../../.. -Wall -W -Wextra nwst.cc -DNDEBUG -O1 -o nwst

ref_filter: ref_filter.cc
	g++ -I../../.. -Wall -W -Wextra ref_filter.cc -DNDEBUG -O1 -o ref_filter

ref_seg: ref_seg.cc
	g++ -I../../.. -Wall -W -Wextra ref_seg.cc -DNDEBUG -O1 -o ref_seg

debug: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra  n_cmpt.cc -g -g3 -o n_cmpt

debug2: n_cmpt2.hh n_cmpt2.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt2.cc -g -g3 -o n_cmpt2

debug3: n_cmpt3.hh n_cmpt3.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt3.cc -g -g3 -o n_cmpt3

Debug4: n_cmpt4.hh n_cmpt4.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt4.cc -g -g3 -o n_cmpt4

Debug5: n_cmpt5.hh n_cmpt5.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt5.cc -g -g3 -o n_cmpt5

Debugnwst: nwst.hh nwst.cc
	g++ -I../../.. -Wall -W -Wextra nwst.cc -g -g3 -o nwst

