n_cmpt: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt.cc -DNDEBUG -O1 -o n_cmpt

n_cmpt2: n_cmpt2.hh n_cmpt2.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt2.cc -DNDEBUG -O1 -o n_cmpt2

n_cmpt3: n_cmpt3.hh n_cmpt3.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt3.cc -DNDEBUG -O1 -o n_cmpt3

debug: n_cmpt.hh n_cmpt.cc
	g++ -I../../.. -Wall -W -Wextra  n_cmpt.cc -g -g3 -o n_cmpt

debug2: n_cmpt2.hh n_cmpt2.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt2.cc -g -g3 -o n_cmpt2

debug3: n_cmpt3.hh n_cmpt3.cc
	g++ -I../../.. -Wall -W -Wextra n_cmpt3.cc -g -g3 -o n_cmpt3
